### ISSUE TITLE
Tabulations used to indent #define (with auto-insertion of header define guards)

### ISSUE THREAD

**Issue by fanfan54** [Hirevo/epitech-c-cpp-headers#8]
Hi,
I think I found a (small) issue with the auto-insertion of header define guards.

If :
* `epitech-c-cpp-headers.headerType` is set to `post2017`
* `epitech-c-cpp-headers.usePragmaOnce` is disabled

Then, when inserting the header in a C/C++ header file, the extension will use **tabulation** to indent the `#define`
![image](https://user-images.githubusercontent.com/11705441/53407415-7620b280-39bc-11e9-91de-4e675b388e57.png)
...but it should use 4 spaces.
![image](https://user-images.githubusercontent.com/11705441/53407435-833da180-39bc-11e9-8039-886b2124f9c7.png)

There is no indentation problem with the `pre2017` coding style.

I'm going to push a pull request...

**Comment by Hirevo** [comment]
Hello,

To begin, thank you for reporting this issue and making the pull request.

Despite knowing that the coding style changed, I completely forgot that tabs were still being inserted.
In third year, we don't get C projects anymore so I guess it's why I didn't noticed it.
I hope it didn't cause any trouble for other people's projects.

I'll go review the pull request. :)
