### ISSUE TITLE
Add Makefile header support for `.mk` files

### ISSUE THREAD

**Issue by C0Florent** [Hirevo/epitech-c-cpp-headers#88]
Usually, Makefiles are named literally "Makefile", "makefile", or "GNUmakefile". But in the case where you have parts of a Makefile contained in a separate file, the convention is to use the `.mk` file extension.

`.mk` files are recognised by the coding style checker as Makefiles and reports "missing header" style errors in these files, but the extension doesn't recognise them as Makefiles and can't automatically add a header to the file.

I think the fix can be made quite easily by changing how files are detected as Makefile or not

**Comment by Hirevo** [comment]
Hi !

I personally never used `.mk` files as part of my Makefiles in my time at EPITECH, and none of my fellow classmates did either, so I was unaware of this being an issue.

Thanks for the heads up on this, by creating this issue, and thanks for going ahead with a PR to address it.

**Comment by C0Florent** [comment]
Thanks for reacting so quickly, I'm happy I could make the fix myself, it was really quite easy. First time I ever edited a typescript file :rofl:
